owner: worldwidepixel
repo: status
user-agent: worldwidepixel_status

sites:
  - name: Main Website
    url: https://worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/website.png
  - name: Badger Legacy
    url: https://badger.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/badger.png
  - name: Badger Staging
    url: https://badger-staging.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/badger.png
  - name: Badger Staging API
    url: https://badger-api-staging.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/badger.png
  - name: StatsView
    url: https://stats.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/statsview.png
  - name: Modwrapped
    url: https://badger.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/modwrapped.png

assignees:
  - worldwidepixel

status-website:
  cname: status.worldwidepixel.ca
  logoUrl: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/status.png
  favicon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/status.png
  name: WorldWidePixel Status
  introTitle: "Status for WorldWidePixel services."
  navbar:
    - title: Home
      href: https://worldwidepixel.ca/
    - title: Status
      href: https://status.worldwidepixel.ca/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
