owner: worldwidepixel
repo: status
user-agent: worldwidepixel_status

sites:
  - name: Main Website
    url: https://worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/website.png
  - name: Badger Legacy (v1)
    url: https://badger.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/badger.png
  - name: Badger v2 (staging)
    url: https://v2.badger.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/badger.png
  - name: Badger v2 API (staging)
    url: https://badger-api-staging.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/badger.png
  - name: Badger v3 (staging)
    url: https://v3.badger.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/badger.png
  - name: Badger v3 API (staging)
    url: https://api.v3.badger.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/badger.png
  - name: StatsView
    url: https://stats.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/statsview.png
  - name: Modwrapped
    url: https://badger.worldwidepixel.ca
    icon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/modwrapped.png

assignees:
  - worldwidepixel

status-website:
  cname: status.worldwidepixel.ca
  logoUrl: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/status.png
  favicon: https://raw.githubusercontent.com/worldwidepixel/status/refs/heads/master/assets/status.png
  name: WorldWidePixel Status
  introTitle: "Status for WorldWidePixel services."
  navbar:
    - title: Home
      href: https://worldwidepixel.ca/
    - title: Status
      href: https://status.worldwidepixel.ca/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: "@import 'https://fonts.bunny.net/css?family=inter:100,200,300,400,500,600,700,800,900'; body {font-family: Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica Neue, sans-serif;}"
